// Mock data fallback when DB not available (for local dev / build)
export const mockCategories = [
  { id: "1", name: "Digital Marketing", slug: "digital-marketing", count: 280, color: "bg-blue-600" },
  { id: "2", name: "UI/UX Design", slug: "ui-ux-design", count: 140, color: "bg-white border" },
  { id: "3", name: "Graphic Design", slug: "graphic-design", count: 245, color: "bg-white border" },
  { id: "4", name: "Web Development", slug: "web-development", count: 206, color: "bg-white border" },
];

export const mockCourses = [
  {
    id: "c1",
    title: "Learn Figma – UI/UX Design Essential Training",
    slug: "learn-figma-ux-essential",
    description: "Master Figma for UI/UX design with hands-on projects and real-world case studies.",
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&h=400&fit=crop",
    level: "BEGINNER" as const,
    duration: "03 WEEKS",
    categoryId: "2",
    category: { name: "UI/UX Design" },
    instructor: "Kevin Perry",
    rating: 4.7,
    lessons: 8,
    students: 1200,
  },
  {
    id: "c2",
    title: "Education Software and PHP and JS System Script",
    slug: "education-software-php-js",
    description: "Build education platforms with PHP and JavaScript from scratch.",
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop",
    level: "BEGINNER" as const,
    duration: "02 WEEKS",
    categoryId: "4",
    category: { name: "Web Development" },
    instructor: "Max Alexis",
    rating: 4.5,
    lessons: 6,
    students: 950,
  },
  {
    id: "c3",
    title: "IT Statistics Data Science and Business Analysis",
    slug: "it-statistics-data-science",
    description: "Learn statistics, data science fundamentals and business analytics.",
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1501504905252-473cdee68f94?w=600&h=400&fit=crop",
    level: "BEGINNER" as const,
    duration: "04 WEEKS",
    categoryId: "1",
    category: { name: "Digital Marketing" },
    instructor: "Kevin Perry",
    rating: 4.7,
    lessons: 10,
    students: 2100,
  },
  {
    id: "c4",
    title: "Advanced Android 12 & Kotlin Development Course",
    slug: "advanced-android-kotlin",
    description: "Become an expert Android developer with Kotlin and Jetpack Compose.",
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7dfb?w=600&h=400&fit=crop",
    level: "INTERMEDIATE" as const,
    duration: "02 WEEKS",
    categoryId: "4",
    category: { name: "Web Development" },
    instructor: "Max Alexis",
    rating: 4.4,
    lessons: 12,
    students: 1800,
  },
  {
    id: "c5",
    title: "Digital Marketing Masterclass - 23 Courses in 1",
    slug: "digital-marketing-masterclass",
    description: "Complete digital marketing bundle covering SEO, social, ads and analytics.",
    price: 49.99,
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    level: "BEGINNER" as const,
    duration: "06 WEEKS",
    categoryId: "1",
    category: { name: "Digital Marketing" },
    instructor: "Sarah Johnson",
    rating: 4.9,
    lessons: 23,
    students: 5400,
  },
  {
    id: "c6",
    title: "Graphic Design Bootcamp: Photoshop & Illustrator",
    slug: "graphic-design-bootcamp",
    description: "From basics to advanced graphic design with Adobe tools.",
    price: 39.99,
    thumbnail: "https://images.unsplash.com/photo-1626785774573-6dd65b279390?w=600&h=400&fit=crop",
    level: "BEGINNER" as const,
    duration: "05 WEEKS",
    categoryId: "3",
    category: { name: "Graphic Design" },
    instructor: "Emma Lee",
    rating: 4.8,
    lessons: 15,
    students: 3200,
  },
];

export const mockPaymentAccounts = [
  {
    id: "pa1",
    title: "Commercial Bank of Ethiopia",
    bankName: "CBE",
    accountNumber: "1000123456789",
    holderName: "EDURA LEARNING PLC",
    instructions: "Please transfer the exact course amount and upload the receipt screenshot. Include your email in the transfer note.",
    isActive: true,
  },
  {
    id: "pa2",
    title: "TeleBirr",
    bankName: "TeleBirr",
    accountNumber: "0912345678",
    holderName: "EDURA LEARNING",
    instructions: "Send money via TeleBirr and upload screenshot with transaction ID visible.",
    isActive: true,
  },
];
